fix version manually and check docker image existence

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -12,6 +12,13 @@ jobs:
         run: |
           # update bridgecrew version
           version=$(curl -s https://pypi.org/pypi/bridgecrew/json  | jq -r '.info.version')
+          url='https://registry.hub.docker.com/v2/repositories/bridgecrew/bridgecrew/tags/'
+          url+=$version
+          exists=$(curl -s -I -o /dev/null -w "%{http_code}" $url)
+          if [[ $exists -ne 200 ]]; then
+            echo "Docker image not found"
+            exit 1
+          fi
           sed -i'.bkp' -e 's/docker:\/\/bridgecrew\/bridgecrew.*'\''/docker:\/\/bridgecrew\/bridgecrew:'"${version}"''\''/g' action.yml
           rm action.yml.bkp
       - uses: stefanzweifel/git-auto-commit-action@v4
